apiVersion: apps/v1
kind: Deployment
metadata:
  name: gocash-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gocash
  template:
    metadata:
      labels:
        app: gocash
    spec:
      containers:
      - name: gocash
        image: atharva284/gocash:latest  # Replace with your actual Docker Hub or ECR image URL
        ports:
          - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: gocash-service
spec:
  selector:
    app: gocash
  ports:
    - protocol: TCP
      port: 80  # External access port
      targetPort: 8080  # Internal container port
  type: LoadBalancer  # Change to NodePort if using Minikube
